apiVersion: v1
kind: Service
metadata:
  name: moderation-srv
spec:
  type: NodePort
  selector:
    app: moderation
  ports:
    - name: posts
      protocol: TCP
      port: 4003
      targetPort: 4003
